/*
*   DO NOT MAKE CHANGES TO THIS FILE
*   THIS FILE WILL BE OVERWRITTEN
*
*   GENERATED BY REACT-SVGS
*   https://github.com/wllkle/react-svgs.git
*/

type Attributes = Record<string, string | object>;

export interface INode {
    name: string,
    type: string,
    value?: string,
    attributes?: Attributes,
    children?: INode[]
}

interface ISVGData {
    [key: string]: {
        name: string,
        attributes?: Attributes,
        children: INode[]
    }
}

export const data: ISVGData = {
    quality1: {
        name: "quality-1",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M5.1,6.02c.18-.31,.52-.52,.9-.52s.72,.21,.9,.52",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M9.1,6.02c.18-.31,.52-.52,.9-.52s.72,.21,.9,.52",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M4.5,8.5c.55,1.4,1.91,2.4,3.5,2.4s2.95-.99,3.5-2.4H4.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    quality2: {
        name: "quality-2",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M8,1.5C4.41,1.5,1.5,4.41,1.5,8s2.91,6.5,6.5,6.5,6.5-2.91,6.5-6.5S11.59,1.5,8,1.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M4.92,10.24c.69,.95,1.81,1.57,3.08,1.57s2.38-.62,3.08-1.57",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "10",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "6",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    quality3: {
        name: "quality-3",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "10.5",
                    x2: "10.5",
                    y2: "10.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M8,1.5C4.41,1.5,1.5,4.41,1.5,8s2.91,6.5,6.5,6.5,6.5-2.91,6.5-6.5S11.59,1.5,8,1.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "10",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "6",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    quality4: {
        name: "quality-4",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M8,1.5C4.41,1.5,1.5,4.41,1.5,8s2.91,6.5,6.5,6.5,6.5-2.91,6.5-6.5S11.59,1.5,8,1.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "6",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "10",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M10.56,10.5c-.68-.62-1.57-1-2.56-1s-1.88,.38-2.56,1",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    }
};

export type SVGTypes = "quality1" |
	"quality2" |
	"quality3" |
	"quality4";

export const SVGTypesArray: SVGTypes[] = [
    "quality1",
	"quality2",
	"quality3",
	"quality4"
];
