/*
*   DO NOT MAKE CHANGES TO THIS FILE
*   THIS FILE WILL BE OVERWRITTEN
*
*   GENERATED BY REACT-SVGS
*   https://github.com/wllkle/react-svgs.git
*/

type Attributes = Record<string, string | object>;

export interface INode {
    name: string,
    type: string,
    value?: string,
    attributes?: Attributes,
    children?: INode[]
}

interface ISvgIconData {
    [key: string]: {
        name: string,
        attributes?: Attributes,
        children: INode[]
    }
}

export const data: ISvgIconData = {
    applicationWindowStroke: {
        name: "application-window-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M2.5,1.5H13.5c.55,0,1,.45,1,1v3H1.5V2.5c0-.55,.45-1,1-1Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M1.5,5.5H14.5v8c0,.55-.45,1-1,1H2.5c-.55,0-1-.45-1-1V5.5h0Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4.5",
                    y1: "8.5",
                    x2: "11.5",
                    y2: "8.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "3.5",
                    x2: "12.5",
                    y2: "3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4.5",
                    y1: "11.5",
                    x2: "11.5",
                    y2: "11.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    bookBookmarkStroke: {
        name: "book-bookmark-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M13.5,4.5c-.83,0-1.5-.67-1.5-1.5s.67-1.5,1.5-1.5H4c-.83,0-1.5,.67-1.5,1.5s.67,1.5,1.5,1.5H13.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M2.5,3V12.5c0,1.1,.9,2,2,2H13.5V4.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "8.5 4.5 8.5 9.5 7 8.5 5.5 9.5 5.5 4.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    buildingStroke: {
        name: "building-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "1",
                    y1: "14.5",
                    x2: "15",
                    y2: "14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "1.5 14.5 1.5 1.5 6.5 1.5 6.5 14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "6.5 3.5 14.5 3.5 14.5 14",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10.5",
                    y1: "14.5",
                    x2: "10.5",
                    y2: "12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8.5",
                    y1: "9.5",
                    x2: "9.5",
                    y2: "9.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8.5",
                    y1: "6.5",
                    x2: "9.5",
                    y2: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "9.5",
                    x2: "12.5",
                    y2: "9.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "6.5",
                    x2: "12.5",
                    y2: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4",
                    y1: "14.5",
                    x2: "4",
                    y2: "12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4",
                    y1: "4.5",
                    x2: "4",
                    y2: "3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4",
                    y1: "7.5",
                    x2: "4",
                    y2: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4",
                    y1: "10.5",
                    x2: "4",
                    y2: "9.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    calendarStroke: {
        name: "calendar-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "1.5",
                    y: "2.5",
                    width: "13",
                    height: "12",
                    rx: "1",
                    ry: "1",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "3.5",
                    y1: "1.5",
                    x2: "3.5",
                    y2: "3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "1.5",
                    x2: "5.5",
                    y2: "3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10.5",
                    y1: "1.5",
                    x2: "10.5",
                    y2: "3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "12.5",
                    y1: "1.5",
                    x2: "12.5",
                    y2: "3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4.5",
                    y1: "7.5",
                    x2: "5.5",
                    y2: "7.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "7.5",
                    y1: "7.5",
                    x2: "8.5",
                    y2: "7.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10.5",
                    y1: "7.5",
                    x2: "11.5",
                    y2: "7.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4.5",
                    y1: "9.5",
                    x2: "5.5",
                    y2: "9.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "7.5",
                    y1: "9.5",
                    x2: "8.5",
                    y2: "9.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10.5",
                    y1: "9.5",
                    x2: "11.5",
                    y2: "9.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "4.5",
                    y1: "11.5",
                    x2: "5.5",
                    y2: "11.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "7.5",
                    y1: "11.5",
                    x2: "8.5",
                    y2: "11.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10.5",
                    y1: "11.5",
                    x2: "11.5",
                    y2: "11.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    caretDownStroke: {
        name: "caret-down-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "1.5 5.5 14.5 5.5 8 12.5 1.5 5.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    checkStroke: {
        name: "check-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "3.5 7.5 6.5 10.5 12.5 4.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    chevronDoubleDownStroke: {
        name: "chevron-double-down-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "13 3 8 8 3 3",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "13 8 8 13 3 8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    chevronDoubleUpStroke: {
        name: "chevron-double-up-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "3 13 8 8 13 13",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "3 8 8 3 13 8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    chevronDownStroke: {
        name: "chevron-down-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "13 5.5 8 10.5 3 5.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    chevronUpStroke: {
        name: "chevron-up-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "3 10.5 8 5.5 13 10.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    circleCheckStroke: {
        name: "circle-check-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "5.5 8.5 7.5 10.5 11.5 6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    circleExclamationPointStroke: {
        name: "circle-exclamation-point-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "11",
                    r: ".25",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8",
                    y1: "5.5",
                    x2: "8",
                    y2: "8.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    circleMinusStroke: {
        name: "circle-minus-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "8",
                    x2: "10.5",
                    y2: "8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "8",
                    x2: "10.5",
                    y2: "8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    circlePlusStroke: {
        name: "circle-plus-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "8",
                    x2: "10.5",
                    y2: "8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "8",
                    x2: "10.5",
                    y2: "8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8",
                    y1: "10.5",
                    x2: "8",
                    y2: "5.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8",
                    y1: "10.5",
                    x2: "8",
                    y2: "5.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    clockStroke: {
        name: "clock-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.25",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "8 4 8 8 11 8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    crossStroke: {
        name: "cross-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "3.5",
                    y1: "3.5",
                    x2: "12.5",
                    y2: "12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "12.5",
                    y1: "3.5",
                    x2: "3.5",
                    y2: "12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    documentClockStroke: {
        name: "document-clock-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "g",
                type: "element",
                children: [
                    {
                        name: "polyline",
                        type: "element",
                        attributes: {
                            points: "5.5 13 5.5 14.5 14.5 14.5 14.5 5.5 10.64 5.5 10.64 1.5 5.5 1.5 5.5 5",
                            fill: "none",
                            stroke: "#2d3741",
                            strokeLinecap: "round",
                            strokeLinejoin: "round",
                            strokeWidth: "1.2"
                        }
                    },
                    {
                        name: "path",
                        type: "element",
                        attributes: {
                            d: "M10.64,1.5l3.86,4L10.64,1.5Z",
                            fill: "none",
                            stroke: "#2d3741",
                            strokeLinecap: "round",
                            strokeLinejoin: "round",
                            strokeWidth: "1.2"
                        }
                    }
                ]
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "5.5 7 5.5 9 7 9",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "5.5",
                    cy: "9",
                    r: "4",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    documentFileStroke: {
        name: "document-file-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "3.5 8.5 3.5 5.5 7.5 1.5 14.5 1.5 14.5 14.5 3.5 14.5 3.5 12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "7.5 2 7.5 5.5 4 5.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "1.5",
                    y: "8.5",
                    width: "9",
                    height: "4",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    envelopeClosedStroke: {
        name: "envelope-closed-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "2",
                    y: "3",
                    width: "12",
                    height: "10",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "2.5 3.5 8 9 13.5 3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "6",
                    y1: "8",
                    x2: "2.5",
                    y2: "12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10",
                    y1: "8",
                    x2: "13.5",
                    y2: "12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    flagTriangleStroke: {
        name: "flag-triangle-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "1.5",
                    y1: "1.5",
                    x2: "1.5",
                    y2: "14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M1.5,2.5C6.5,.5,7.5,6.5,14.5,6.5c-7,7-8,0-13,4V2.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    folderClosedStroke: {
        name: "folder-closed-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "2 2.5 2 13.5 14 13.5 14 4.5 7 4.5 7 2.5 2 2.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    gearStroke: {
        name: "gear-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M14.5,8.6v-1.46c0-.26-.18-.49-.43-.55l-1.47-.37c-.07-.17-.14-.34-.23-.5l.72-1.21c.13-.22,.1-.51-.08-.69l-1.03-1.03c-.18-.18-.47-.22-.69-.09l-1.29,.78c-.17-.07-.34-.14-.52-.2l-.34-1.36c-.06-.25-.29-.43-.55-.43h-1.46c-.26,0-.49,.18-.55,.43l-.37,1.47c-.17,.07-.34,.14-.5,.23l-1.21-.72c-.22-.13-.51-.1-.69,.09l-1.03,1.03c-.18,.18-.22,.47-.09,.69l.78,1.29c-.07,.17-.14,.34-.2,.52l-1.36,.34c-.25,.06-.43,.29-.43,.55v1.46c0,.26,.18,.49,.43,.55l1.47,.37c.07,.17,.14,.34,.23,.5l-.72,1.21c-.13,.22-.1,.51,.09,.69l1.03,1.03c.18,.18,.47,.22,.69,.09l1.29-.78c.17,.07,.34,.14,.52,.2l.34,1.36c.06,.25,.29,.43,.55,.43h1.46c.26,0,.49-.18,.55-.43l.37-1.47c.17-.07,.34-.14,.5-.23l1.21,.72c.22,.13,.51,.1,.69-.08l1.03-1.03c.18-.18,.22-.47,.09-.69l-.78-1.29c.07-.17,.14-.34,.2-.52l1.36-.34c.25-.06,.43-.29,.43-.55Zm-4-.6c0,1.38-1.12,2.5-2.5,2.5s-2.5-1.12-2.5-2.5,1.12-2.5,2.5-2.5,2.5,1.12,2.5,2.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    globeGridStroke: {
        name: "globe-grid-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "ellipse",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    rx: "3",
                    ry: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "14",
                    y1: "5.5",
                    x2: "2",
                    y2: "5.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "14",
                    y1: "10.5",
                    x2: "2",
                    y2: "10.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    hourGlassStroke: {
        name: "hour-glass-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "2.5",
                    y1: "1.5",
                    x2: "13.5",
                    y2: "1.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "2.5",
                    y1: "14.5",
                    x2: "13.5",
                    y2: "14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M3.5,14.5v-2c0-1.27,.67-2.38,1.69-2.99h0c.49-.32,.81-.88,.81-1.51,0-.63-.32-1.18-.81-1.51h0c-1.01-.61-1.69-1.73-1.69-2.99V1.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M12.5,14.5v-2c0-1.27-.67-2.38-1.69-2.99h0c-.49-.32-.81-.88-.81-1.51,0-.63,.32-1.18,.81-1.51h0c1.01-.61,1.69-1.73,1.69-2.99V1.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M12.5,14c-1.11-1.24-2.71-3.5-4.5-3.5s-3.39,2.26-4.5,3.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    infoModelStroke: {
        name: "info-model-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8",
                    y1: "6.5",
                    x2: "8",
                    y2: "12.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "3.5",
                    y: "1.5",
                    width: "9",
                    height: "5",
                    rx: ".5",
                    ry: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M3,12.5v-2c0-.55,.45-1,1-1H12c.55,0,1,.45,1,1v2",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "1.5",
                    y: "12.5",
                    width: "3",
                    height: "2",
                    rx: ".5",
                    ry: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "6.5",
                    y: "12.5",
                    width: "3",
                    height: "2",
                    rx: ".5",
                    ry: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "11.5",
                    y: "12.5",
                    width: "3",
                    height: "2",
                    rx: ".5",
                    ry: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    laptopCursorStroke: {
        name: "laptop-cursor-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "2.5",
                    y: "1.5",
                    width: "11",
                    height: "9",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "14.5 14.5 1.5 14.5 2.5 10.5 13.5 10.5 14.5 14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "7.75 6.5 6.5 7.5 6.5 3.5 9.5 6.5 7.75 6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "7.84",
                    y1: "6.84",
                    x2: "8.5",
                    y2: "8.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    linkExternalOutlineBold: {
        name: "link-external-outline-bold",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M13.5,1.5h-5V3.5h2.59L6.63,7.96l1.42,1.41,4.45-4.46v2.58h2V2.5c0-.55-.45-1-1-1Z",
                    fill: "#2d3741"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M11.5,12.5H3.5V4.5h3.5V2.5H2.5c-.55,0-1,.45-1,1V13.5c0,.55,.45,1,1,1H12.5c.55,0,1-.45,1-1v-4.5h-2v3.5Z",
                    fill: "#2d3741"
                }
            }
        ]
    },
    linkExternalOutlineRegular: {
        name: "link-external-outline-regular",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M13.5,1.9h-4.6v1.2h3.15L7.2,7.96l.85,.85L12.9,3.95v3.15h1.2V2.5c0-.33-.27-.6-.6-.6Z",
                    fill: "#2d3741"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M11.9,12.9H3.1V4.1h3.5v-1.2H2.5c-.33,0-.6,.27-.6,.6V13.5c0,.33,.27,.6,.6,.6H12.5c.33,0,.6-.27,.6-.6v-4.1h-1.2v3.5Z",
                    fill: "#2d3741"
                }
            }
        ]
    },
    listAscendingStroke: {
        name: "list-ascending-stroke",
        attributes: {
            id: "sketching",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "defs",
                type: "element",
                children: [
                    {
                        name: "style",
                        type: "print",
                        value: ".cls-1{fill:none;stroke:#2d3741;stroke-linecap:square;stroke-linejoin:round;stroke-width:1.2px}"
                    }
                ]
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "13.52",
                    x2: "1.5",
                    y2: "13.52"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8.5",
                    y1: "10",
                    x2: "1.5",
                    y2: "10"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "6.52",
                    x2: "1.5",
                    y2: "6.52"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "8.5 4.5 11.5 1.5 14.5 4.5"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "10",
                    x2: "11.5",
                    y2: "2.5"
                }
            }
        ]
    },
    listDescendingStroke: {
        name: "list-descending-stroke",
        attributes: {
            id: "sketching",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "defs",
                type: "element",
                children: [
                    {
                        name: "style",
                        type: "print",
                        value: ".cls-1{fill:none;stroke:#2d3741;stroke-linecap:square;stroke-linejoin:round;stroke-width:1.2px}"
                    }
                ]
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "2.52",
                    x2: "1.5",
                    y2: "2.52"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8.5",
                    y1: "6",
                    x2: "1.5",
                    y2: "6"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "9.52",
                    x2: "1.5",
                    y2: "9.52"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "14.46 11.5 11.46 14.5 8.46 11.5"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "6",
                    x2: "11.5",
                    y2: "13.5"
                }
            }
        ]
    },
    listUnsortedStroke: {
        name: "list-unsorted-stroke",
        attributes: {
            id: "sketching",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "defs",
                type: "element",
                children: [
                    {
                        name: "style",
                        type: "print",
                        value: ".cls-1{fill:none;stroke:#2d3741;stroke-linecap:square;stroke-linejoin:round;stroke-width:1.2px}"
                    }
                ]
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8.5",
                    y1: "4.52",
                    x2: "1.5",
                    y2: "4.52"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "14.5",
                    y1: "8",
                    x2: "1.5",
                    y2: "8"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "11.5",
                    y1: "11.52",
                    x2: "1.5",
                    y2: "11.52"
                }
            }
        ]
    },
    lockLockedStroke: {
        name: "lock-locked-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M5,7.5v-2c0-1.66,1.34-3,3-3s3,1.34,3,3v2",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "3.5",
                    y: "7.5",
                    width: "9",
                    height: "7",
                    rx: "1",
                    ry: "1",
                    transform: "translate(16 22) rotate(-180)",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "6.94",
                    y1: "12.06",
                    x2: "9.06",
                    y2: "9.94",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "9.06",
                    y1: "12.06",
                    x2: "6.94",
                    y2: "9.94",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    lockOpenStroke: {
        name: "lock-open-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M9,7v-2.5c0-1.66,1.34-3,3-3s3,1.34,3,3",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "1.5",
                    y: "7.5",
                    width: "9",
                    height: "7",
                    rx: "1",
                    ry: "1",
                    transform: "translate(12 22) rotate(-180)",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "4.5 11 5.54 12.04 7.5 10",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    lockSemiOpenStroke: {
        name: "lock-semi-open-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M11,7v-2.5c0-1.66-1.34-3-3-3s-3,1.34-3,3",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "3.5",
                    y: "7.5",
                    width: "9",
                    height: "7",
                    rx: "1",
                    ry: "1",
                    transform: "translate(16 22) rotate(-180)",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "6.5",
                    y1: "11",
                    x2: "9.5",
                    y2: "11",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    magnifyingGlassStroke: {
        name: "magnifying-glass-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "6.5",
                    cy: "6.5",
                    r: "5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10.25",
                    y1: "10.25",
                    x2: "14.5",
                    y2: "14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    mapPinStroke: {
        name: "map-pin-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "10.51",
                    cy: "3.43",
                    r: "2",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "10.51",
                    y1: "5.43",
                    x2: "10.51",
                    y2: "8.43",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "12.51 3.43 14.49 4.43 14.49 14.57 10.51 12.43 5.51 14.43 1.51 12.31 1.51 2.43 5.51 4.43 8.52 3.22",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    pencilSlashStroke: {
        name: "pencil-slash-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "1.5 14.5 1.5 11.5 11.5 1.5 14.5 4.5 4.5 14.5 1.5 14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "9",
                    y1: "4",
                    x2: "12",
                    y2: "7",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "2.5",
                    y1: "2.5",
                    x2: "13.5",
                    y2: "13.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    pencilStroke: {
        name: "pencil-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "1.5 14.5 1.5 11.5 11.5 1.5 14.5 4.5 4.5 14.5 1.5 14.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "9",
                    y1: "4",
                    x2: "12",
                    y2: "7",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    pinLocationStroke: {
        name: "pin-location-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M12.5,6c0-2.49-2.01-4.5-4.5-4.5S3.5,3.51,3.5,6c0,3.27,4.5,8.5,4.5,8.5,0,0,4.5-5.23,4.5-8.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "6",
                    r: "1.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    semicheckedStroke: {
        name: "semichecked-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "3.5",
                    y1: "8",
                    x2: "12.5",
                    y2: "8",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    shieldLockLockedStroke: {
        name: "shield-lock-locked-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M6.5,7.5v-1.5c0-.83,.67-1.5,1.5-1.5s1.5,.67,1.5,1.5v1.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "5.5",
                    y: "7.5",
                    width: "5",
                    height: "4",
                    rx: "1",
                    ry: "1",
                    transform: "translate(16 19) rotate(-180)",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M8,14.5c5.5-1,6.5-8,6.5-11-2,0-4,0-6.5-2.04C5.5,3.5,3.5,3.5,1.5,3.5c0,3,1,10,6.5,11Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    smileyExcitedStroke: {
        name: "smiley-excited-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "8",
                    r: "6.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M5.1,6.02c.18-.31,.52-.52,.9-.52s.72,.21,.9,.52",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M9.1,6.02c.18-.31,.52-.52,.9-.52s.72,.21,.9,.52",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M4.5,8.5c.55,1.4,1.91,2.4,3.5,2.4s2.95-.99,3.5-2.4H4.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    smileyHappyStroke: {
        name: "smiley-happy-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M8,1.5C4.41,1.5,1.5,4.41,1.5,8s2.91,6.5,6.5,6.5,6.5-2.91,6.5-6.5S11.59,1.5,8,1.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M4.92,10.24c.69,.95,1.81,1.57,3.08,1.57s2.38-.62,3.08-1.57",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "10",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "6",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    smileyNeutralStroke: {
        name: "smiley-neutral-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "5.5",
                    y1: "10.5",
                    x2: "10.5",
                    y2: "10.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M8,1.5C4.41,1.5,1.5,4.41,1.5,8s2.91,6.5,6.5,6.5,6.5-2.91,6.5-6.5S11.59,1.5,8,1.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "10",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "6",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    smileySadStroke: {
        name: "smiley-sad-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M8,1.5C4.41,1.5,1.5,4.41,1.5,8s2.91,6.5,6.5,6.5,6.5-2.91,6.5-6.5S11.59,1.5,8,1.5Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "6",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "10",
                    cy: "7",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M10.56,10.5c-.68-.62-1.57-1-2.56-1s-1.88,.38-2.56,1",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    speakBubbleLettersStroke: {
        name: "speak-bubble-letters-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M11.5,11.5l-3,3v-3H3.5c-1.1,0-2-.9-2-2V3.5c0-1.1,.9-2,2-2H12.5c1.1,0,2,.9,2,2v6c0,1.1-.9,2-2,2h-1Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M5.5,8.5v-3c0-.55-.45-1-1-1h0",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "7.5",
                    y1: "3.5",
                    x2: "7.5",
                    y2: "8.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M7.5,4.5h1c.55,0,1,.45,1,1v2c0,.55-.45,1-1,1h-1V4.5h0Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M12.5,8.5c-.55,0-1-.45-1-1v-2c0-.55,.45-1,1-1",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M3.5,6.5h1c.55,0,1,.45,1,1h0c0,.55-.45,1-1,1h-1v-2h0Z",
                    transform: "translate(9 15) rotate(-180)",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    squareInfoStroke: {
        name: "square-info-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "2.5",
                    y: "2.5",
                    width: "11",
                    height: "11",
                    rx: ".92",
                    ry: ".92",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "round",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "polyline",
                type: "element",
                attributes: {
                    points: "8 10.5 8 7.5 7 7.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "7.75",
                    cy: "5",
                    r: ".25",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "7",
                    y1: "10.5",
                    x2: "9",
                    y2: "10.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    squareThreeStroke: {
        name: "square-three-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "rect",
                type: "element",
                attributes: {
                    x: "5.5",
                    y: "5.5",
                    width: "9",
                    height: "9",
                    rx: "1",
                    ry: "1",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M5.5,12.5h-1c-.55,0-1-.45-1-1V4.5c0-.55,.45-1,1-1h7c.55,0,1,.45,1,1v1",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M3.5,10.5h-1c-.55,0-1-.45-1-1V2.5c0-.55,.45-1,1-1h7c.55,0,1,.45,1,1v1",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    starStroke: {
        name: "star-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "8 12.07 3.98 14.18 4.75 9.71 1.5 6.54 5.99 5.89 8 1.82 10.01 5.89 14.5 6.54 11.25 9.71 12.02 14.18 8 12.07",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    tagStroke: {
        name: "tag-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "polygon",
                type: "element",
                attributes: {
                    points: "1.5 9.5 6.5 14.5 14.5 6.5 14.5 1.5 9.38 1.5 1.5 9.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "12",
                    cy: "4",
                    r: ".5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    telephoneAnalogStroke: {
        name: "telephone-analog-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M14.05,12c-.1,.49-.25,.89-.47,1.22-.23,.35-.53,.63-.92,.84-.53,.29-1.11,.44-1.73,.44-.46,0-.95-.08-1.46-.25-1.03-.33-2.01-.96-2.76-1.46-.72-.49-1.38-1.1-2.02-1.87-.68-.74-1.2-1.47-1.59-2.25-.41-.8-.9-1.86-1.09-2.93-.22-1.23-.02-2.28,.61-3.14,.26-.36,.57-.62,.95-.8,.36-.17,.77-.27,1.27-.31,.29-.02,.68,.06,.91,.55,.18,.39,.38,.79,.56,1.18,.13,.28,.27,.56,.41,.85,.09,.18,.16,.37,.21,.55,.11,.36,.01,.65-.3,.9-.4,.32-.79,.63-1.17,.95-.01,.01-.04,.04-.06,.06,0,.02,.02,.06,.04,.12,.38,.94,.85,1.71,1.42,2.36h0c.56,.66,1.27,1.22,2.15,1.73,.06,.03,.09,.05,.11,.06,.02-.02,.05-.04,.06-.05,.36-.33,.72-.68,1.09-1.03,.29-.28,.59-.34,.93-.18,.17,.08,.35,.17,.51,.28,.26,.17,.53,.34,.79,.51,.36,.24,.73,.48,1.1,.71,.46,.29,.48,.69,.43,.98Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    },
    triangleExclamationPointStroke: {
        name: "triangle-exclamation-point-stroke",
        attributes: {
            id: "stroke",
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 16 16"
        },
        children: [
            {
                name: "path",
                type: "element",
                attributes: {
                    d: "M14.42,12.61L8.51,2.52c-.23-.39-.79-.39-1.02,0L1.58,12.61c-.23,.4,.05,.89,.51,.89H13.91c.46,0,.74-.5,.51-.89Z",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeMiterlimit: "10",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "circle",
                type: "element",
                attributes: {
                    cx: "8",
                    cy: "11",
                    r: ".25",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            },
            {
                name: "line",
                type: "element",
                attributes: {
                    x1: "8",
                    y1: "6.5",
                    x2: "8",
                    y2: "8.5",
                    fill: "none",
                    stroke: "#2d3741",
                    strokeLinecap: "square",
                    strokeLinejoin: "round",
                    strokeWidth: "1.2"
                }
            }
        ]
    }
};

export type SvgIconTypes = "applicationWindowStroke" |
	"bookBookmarkStroke" |
	"buildingStroke" |
	"calendarStroke" |
	"caretDownStroke" |
	"checkStroke" |
	"chevronDoubleDownStroke" |
	"chevronDoubleUpStroke" |
	"chevronDownStroke" |
	"chevronUpStroke" |
	"circleCheckStroke" |
	"circleExclamationPointStroke" |
	"circleMinusStroke" |
	"circlePlusStroke" |
	"clockStroke" |
	"crossStroke" |
	"documentClockStroke" |
	"documentFileStroke" |
	"envelopeClosedStroke" |
	"flagTriangleStroke" |
	"folderClosedStroke" |
	"gearStroke" |
	"globeGridStroke" |
	"hourGlassStroke" |
	"infoModelStroke" |
	"laptopCursorStroke" |
	"linkExternalOutlineBold" |
	"linkExternalOutlineRegular" |
	"listAscendingStroke" |
	"listDescendingStroke" |
	"listUnsortedStroke" |
	"lockLockedStroke" |
	"lockOpenStroke" |
	"lockSemiOpenStroke" |
	"magnifyingGlassStroke" |
	"mapPinStroke" |
	"pencilSlashStroke" |
	"pencilStroke" |
	"pinLocationStroke" |
	"semicheckedStroke" |
	"shieldLockLockedStroke" |
	"smileyExcitedStroke" |
	"smileyHappyStroke" |
	"smileyNeutralStroke" |
	"smileySadStroke" |
	"speakBubbleLettersStroke" |
	"squareInfoStroke" |
	"squareThreeStroke" |
	"starStroke" |
	"tagStroke" |
	"telephoneAnalogStroke" |
	"triangleExclamationPointStroke";

export const SvgIconTypesArray: SvgIconTypes[] = [
    "applicationWindowStroke",
	"bookBookmarkStroke",
	"buildingStroke",
	"calendarStroke",
	"caretDownStroke",
	"checkStroke",
	"chevronDoubleDownStroke",
	"chevronDoubleUpStroke",
	"chevronDownStroke",
	"chevronUpStroke",
	"circleCheckStroke",
	"circleExclamationPointStroke",
	"circleMinusStroke",
	"circlePlusStroke",
	"clockStroke",
	"crossStroke",
	"documentClockStroke",
	"documentFileStroke",
	"envelopeClosedStroke",
	"flagTriangleStroke",
	"folderClosedStroke",
	"gearStroke",
	"globeGridStroke",
	"hourGlassStroke",
	"infoModelStroke",
	"laptopCursorStroke",
	"linkExternalOutlineBold",
	"linkExternalOutlineRegular",
	"listAscendingStroke",
	"listDescendingStroke",
	"listUnsortedStroke",
	"lockLockedStroke",
	"lockOpenStroke",
	"lockSemiOpenStroke",
	"magnifyingGlassStroke",
	"mapPinStroke",
	"pencilSlashStroke",
	"pencilStroke",
	"pinLocationStroke",
	"semicheckedStroke",
	"shieldLockLockedStroke",
	"smileyExcitedStroke",
	"smileyHappyStroke",
	"smileyNeutralStroke",
	"smileySadStroke",
	"speakBubbleLettersStroke",
	"squareInfoStroke",
	"squareThreeStroke",
	"starStroke",
	"tagStroke",
	"telephoneAnalogStroke",
	"triangleExclamationPointStroke"
];
