version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Maintain dependencies for pip, pipenv, poetry
  - package-ecosystem: "node"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"