name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - master

jobs:
  github-pages-deployment:
    name: Build storybook and deploy latest version to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build and deploy Storybook to GitHub Pages
        run: npm run storybook:deploy
