name: Deploy to Chromatic

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic-deployment:
    name: Build storybook and deploy current build to Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.5
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap lerna dependencies
        run: npx lerna bootstrap
      - name: Build components
        run: npx lerna run build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
