name: Deploy to Chromatic

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic-deployment:
    name: Build storybook and deploy current build to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Bootstrap lerna dependencies
        run: npx lerna bootstrap --loglevel silly

      - name: Build components
        run: npx lerna run build

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build

      - name: Comment on PR with chromatic result
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Chromatic
          message: |
            ${{ steps.chromatic.outputs.buildUrl }}
