name: Deploy to NPM

on:
  push:
    branches:
      - main

jobs:
  npm-deployment:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Build and deploy changed components to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Bootstrap lerna dependencies
        run: npx lerna bootstrap

      - name: Build and deploy changed components to NPM
        run: npx lerna publish --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
