name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows:
      - Deploy to NPM
    types:
      - completed

jobs:
  github-pages-deployment:
    name: Build storybook and deploy latest version to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.5
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap lerna dependencies
        run: npx lerna bootstrap
      - name: Build components
        run: npx lerna run build
      - name: Build and deploy Storybook to GitHub Pages
        run: npm run storybook:deploy
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
