name: Deploy to Chromatic

on:
  push:
    branches-ignore:
      - 'develop'

jobs:
  chromatic-deployment:
    name: Build storybook and deploy current build to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Bootstrap lerna dependencies
        run: npx lerna bootstrap --loglevel silly

      - name: Build components
        run: npx lerna run build

      - name: Publish to Chromatic
        if: github.ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        uses: chromaui/action@v10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build

      - name: Publish to Chromatic and auto accept changes
        if: github.ref == 'refs/heads/main' || github.actor == 'dependabot[bot]'
        uses: chromaui/action@v10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
          autoAcceptChanges: true